(package "scala-ts-mode"
         "1.0.0"
         "An tree-sitter based major-mode for Scala")

(website-url "https://github.com/KaranAhlawat/scala-ts-mode")
(keywords "emacs" "tree-sitter" "scala" "scala-ts-mode" "languages")

(package-file "scala-ts-mode.el")
(files "scala-ts-mode.el" "scala-ts-mode-autoloads.el" "scala-ts-mode-pkg.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")
