name: CI

on:
  push:
    branches:
      - main
      - "ci/**"

  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - release-snapshot
        ignore_warnings:
          - true
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: "scala-ts-mode.el"
          ignore_warnings: false
          warnings_as_errors: false
